# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: attack-rtr5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attack-rtr5
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr3-svc
      labels:
        app: attack-rtr5
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        args:
        - |-
          sleep 10000
        env:
        - name: IP_ADDR
          value: 211.121.232.14
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 211.0.0.1
        - name: INT
          value: net1
        image: master:5000/kali
        name: attack-rtr5
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /root
          name: rtr3-attacker
      initContainers: []
      volumes:
      - name: rtr3-attacker
        nfs:
          path: /configs/attack/rtr3-attacker
          server: storage


