# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ntp-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntp-pool
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr1-svc
      labels:
        app: ntp-pool
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 107.15.121.121
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 107.0.0.1
        - name: INT
          value: net1
        image: master:5000/ntpd
        name: ntp-pool
        securityContext:
          privileged: true
        volumeMounts: []
      initContainers: []
      volumes: []


