# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rtr-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtr-03
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: bgp, bgp, rtr3-svc, external
      labels:
        app: rtr-03
    spec:
      containers:
      - env: []
        image: master:5000/frr
        name: rtr-03
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/frr
          name: rtr-03
      initContainers: []
      volumes:
      - name: rtr-03
        nfs:
          path: /configs/network/rtr-03
          server: storage


