# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www-sabaq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www-sabaq
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr3-svc
      labels:
        app: www-sabaq
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 105.16.44.64
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 105.0.0.1
        - name: INT
          value: net1
        image: master:5000/nginx
        name: www-sabaq
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: sabq-org
      initContainers: []
      volumes:
      - name: sabq-org
        nfs:
          path: /configs/web/sabq.org
          server: storage


