# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www-wikipedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www-wikipedia
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr1-svc
      labels:
        app: www-wikipedia
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 208.80.154.224
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 208.0.0.1
        - name: INT
          value: net1
        image: master:5000/nginx
        name: www-wikipedia
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: wikipedia-org
      initContainers: []
      volumes:
      - name: wikipedia-org
        nfs:
          path: /configs/web/wikipedia.org
          server: storage


